name: CI

on:
  push:
    branches:
    - main
  schedule:
  - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  gnu:
    name: Check progression of naari3/nomifactory-ja
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
    - run: npm ci

    - name: Get translated result
      run: npm run start

    - name: Add & Commit the result
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: "Refresh the result json"
        add: translated-result.json

    - name: Generate graph
      run: npm run graph

    - name: Add & Commit the graph
      uses: EndBug/add-and-commit@v9.1.1
      with:
        default_author: github_actions
        message: "Refresh the result graph"
        add: translated-result.png
